# Generated by Django 5.0.7 on 2024-10-13 18:12

import kars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[kars.models.validate_year])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.DeleteModel(
            name='Kar',
        ),
    ]
